apiVersion: apps/v1
kind: Deployment
metadata:
  name: apa000dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apa000kube
  template:
    metadata:
      labels:
        app: apa000kube
    spec:
      containers:
        - name: apa000ex91
          image: httpd
          ports:
            - containerPort: 80