apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort

---

apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  containers:
    - name: my-app
      image: yoonjeong/my-app:1.0
      ports:
        - containerPort: 8080
      resources:
        limits:
          memory: "64Mi"
          cpu: "50m"

---

apiVersion: v1
kind: Pod
metadata:
  name: web-server
  labels:
    name: nginx
spec:
  volumes:  # Pod에서 사용할 볼륨 목록 선언
    - name: app-config # 컨테이너에서 참조할 볼륨 이름
      configMap:
        name: nginx-config # 참조할 ConfigMap 이름
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts: # 컨테이너에서 Pod 볼륨 마운트 선언
        - mountPath: /etc/nginx/conf.d # 컨테이너 안에서 마운팅할 경로
          name: app-config # 마운팅할 Pod 볼륨 이름
      resources:
        limits:
          memory: "64Mi"
          cpu: "50m"